# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Contact'),
        ),
    ]
