# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='phone_number',
            field=models.IntegerField(max_length=1000),
        ),
    ]
