# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20160627_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='phone_number',
            field=models.CharField(max_length=100),
        ),
    ]
