# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 05:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20160627_1053'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
