# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 05:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_entry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
