# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-29 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bhavcopy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bhav_date', models.DateField()),
                ('sc_code', models.IntegerField()),
                ('sc_name', models.CharField(max_length=200)),
                ('sc_group', models.CharField(max_length=10)),
                ('sc_type', models.CharField(max_length=10)),
                ('open', models.FloatField(max_length=20)),
                ('high', models.FloatField(max_length=200)),
                ('low', models.FloatField(max_length=200)),
                ('close', models.FloatField(max_length=200)),
                ('last', models.FloatField(max_length=200)),
                ('prevclose', models.FloatField(max_length=200)),
                ('no_trades', models.IntegerField()),
                ('no_of_shrs', models.IntegerField()),
                ('net_turnov', models.FloatField(max_length=200)),
                ('tdcloindi', models.CharField(max_length=200)),
            ],
        ),
    ]
