# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_bhavcopy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files_Upload_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
    ]
