# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_files_upload_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio_Video_models',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(max_length=200, upload_to=b'')),
                ('video', models.FileField(max_length=300, upload_to=b'')),
            ],
        ),
    ]
